name: if-2
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: exit 1
        run: exit 1
      - name: echo
        run: echo hello
  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
      - name: echo
        run: echo hello