name: issues-workflow
on:
  issues:
    types: [opened]

jobs:
  issues-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello github
          echo hello actions